### ISSUE TITLE
RobotDriveCommand uses tankDrive when arcadeDrive would be more suitable

### ISSUE THREAD

**Issue by BrennanColberg** [frc3268/T-Shirt-Cannon-2018#2]
For a single joystick which controls the driving with its two X and Y axes, the arcadeDrive-style driving is far preferable; tankDrive is designed for two joysticks, which is not the case here. I would recommend adding arcadeDrive functionality to DriveTrainSubsystem and implementing it in DrivingCommand.

**Comment by Volcore001** [comment]
Should be fixed
