### ISSUE TITLE
ShootingSubsystem should be broken into PneumaticsSubsystem and Aiming/TargetingSubsystem

### ISSUE THREAD

**Issue by BrennanColberg** [frc3268/T-Shirt-Cannon-2018#3]
The specific names of the new would-be subsystems are arbitrary, but the idea is there. ShootingSubsystem currently handles both aiming and firing, which although operating on the same physical object are two completely independent processes. Hence, they should be broken up into subsystems that reflect this; one to handle all the pneumatics (compressor and solenoid), and one to handle the aiming (raising/lowering motor).

**Comment by Volcore001** [comment]
Fixed
