### ISSUE TITLE
No compressor used

### ISSUE THREAD

**Issue by BrennanColberg** [frc3268/T-Shirt-Cannon-2018#4]
No compressor is ever used or even defined; hence, there will be no pressure and the robot will not work. Use `new Compressor()` to define a compressor, `[Compressor].start()` to start it, and `[Compressor].stop()` to pause it. The compressor will automatically throttle itself at ~120 PSI (iirc) if left to run indefinitely; to this end, be sure the automatic pressure detector gauge thing is set up on the PCM on the robot.

**Comment by Volcore001** [comment]
Where do you recommend implementing the compressor in?

**Comment by Volcore001** [comment]
Should be fixed
