### ISSUE TITLE
ShootingSubsystem has encapsulation issues

### ISSUE THREAD

**Issue by BrennanColberg** [frc3268/T-Shirt-Cannon-2018#5]
Make sure that all Subsystems are interacted with only by their defined methods! Currently, ShootingSubsystem's fields `motor` and `shooter` are used directly by `RaiseCannonCommand`, `LowerCannonCommand`, and `SetShooterCommand`! This should not be the case; methods should be explicitly defined within ShootingSubsystem (or whichever system an object is stored).

**Comment by Volcore001** [comment]
Fixed
